// Copyright (c) 2023-2026 Dan O’Malley
// This file is licensed under the MIT License. See LICENSE for details.


typedef unsigned int uint32_t;
typedef unsigned short uint16_t;
typedef unsigned char uint8_t;

// Memory Locations
#define USER_SPACE_BASE 0x0
#define KEYBOARD_BUFFER 0x1000
#define COMMAND_BUFFER ((uint8_t *)0x1040)
#define USER_PID_INFO 0x2000
#define OPEN_BUFFER_TABLE ((uint8_t *)0x2D00)
#define REQUESTED_INODE_LOC 0x2E00
#define USER_TOTAL_INTERRUPTS_COUNT_LOC 0x2FE4
#define CURRENT_FILE_DESCRIPTOR_PTR ((uint8_t *)0x2FE8)
#define RUNNING_PID_LOC ((uint8_t *)0x2FF0)
#define RETURNED_MMAP_PAGE_LOC ((uint8_t *)0x2FF4)
#define CURRENT_FILE_DESCRIPTOR ((uint8_t *)0x2FF8)
#define STDERR_BUFFER 0x3000
#define SECOND_PROC_TMP_STACK 0x5000
#define SECOND_PROC_SIPI_CODE 0x6000
#define GDT_LOC 0x7000
#define USER_TEMP_INODE_LOC ((uint8_t *)0x30000)
#define USER_TEMP_FILE_LOC ((uint8_t *)0x31000)
#define VIDEO_AND_BIOS_RESERVED_START 0xA0000
#define VIDEO_RAM ((uint8_t *)0xb8000)
#define SHELL_CURSOR_POS 0xb9b88
#define VIDEO_AND_BIOS_RESERVED_END 0xFFFFF
#define TEMP_FILE_START_LOC 0x210000
#define USERPROG_START 0x400000
#define USER_HEAP 0x600000
#define SHARED_LIBRARIES_START_LOC 0x700000
#define STACK_PAGE 0x7FE000
#define STACK_START_LOC 0x7FEFF0
#define USER_SPACE_LIMIT 0x7FFFFF
#define KERNEL_BASE 0x800000
#define PROCESS_TABLE_LOC 0x920000
#define EXT2_INDIRECT_BLOCK ((uint8_t *)0x949000)
#define KERNEL_TEMP_INODE_LOC ((uint8_t *)0x950000)
#define KERNEL_TEMP_FILE_LOC ((uint8_t *)0x960000)
#define INTERRUPT_DESC_TABLE 0x992000
#define INTERRUPT_DESC_TABLE_REG 0x993000
#define TOTAL_INTERRUPTS_COUNT_LOC 0x997000
#define GLOBAL_OBJECT_TABLE 0x998000
#define KERNEL_HASH_LOC ((uint8_t *)0x99A000)
#define LOGIN_COMPLETE ((uint8_t *)0x99A0F0)
#define LOGGED_IN_USER ((uint8_t *)0x99A100)
#define KERNEL_STACK_AP 0x99C000
#define KERNEL_STACK_BSP 0x99F000
#define EXT2_TEMP_INODE_STRUCTS ((uint8_t *)0x9A0000)
#define EXT2_BLOCK_USAGE_MAP 0x9F0000
#define EXT2_INODE_USAGE_MAP 0x9F1000
#define EXT2_INDIRECT_BLOCK_TMP_LOC 0x9F2000
#define SECTOR_AND_BLOCK_VIEWER_BUF_LOC 0x9F5000
#define KERNEL_CONFIGURATION 0x9FC000
#define KERNEL_CACHE_MISSES 0x9FC040
#define KERNEL_CACHE_HITS 0x9FC044
#define NETWORK_PACKETS_TRANSMITTED 0x9FC048
#define NETWORK_PACKETS_RECEIVED 0x9FC04C
#define SECOND_PROC_STARTUP_FUNC_LOC 0x9FC100
#define CURRENT_PROC_RUNNING_LOC 0x9FC104
#define SECOND_PROC_TICK_COUNT_LOC 0x9FC110
#define AP_PID_WAIT_FLAG_LOC 0x9FC118
#define KERNEL_SEMAPHORE_TABLE 0x9FD000
#define PAGE_DIR_BASE 0xA00000
#define PAGE_TABLE_BASE 0xA01000
#define PAGEFRAME_MAP_BASE 0xAD0000
#define DISK_READ_CACHE_LOC ((uint8_t *)0xB00000)
#define DISK_READ_CACHE_DATA ((uint8_t *)0xB01000)
#define NETWORK_INCOMING_RCV_BUFFER 0xC00000
#define NETWORK_INCOMING_RCV_BUFFER_SIZE 0x5000
#define NETWORK_INCOMING_PAYLOAD_BUFFER 0xC05000
#define NETWORK_INCOMING_PAYLOAD_BUFFER_SIZE 0x5000
#define KERNEL_WORKING_DIR_TEMP_INODE_LOC ((uint8_t *)0xC10000)
#define KERNEL_WORKING_DIR ((uint8_t *)0xC18000)
#define VGA_CUSTOM_FONT 0xD00000
#define SUPERBLOCK_LOC ((uint8_t *)0xD05000)
#define BLOCK_GROUP_DESCRIPTOR_TABLE ((uint8_t *)0xD10000)
#define KERNEL_HEAP 0xF00000
#define KERNEL_LOG_LOC 0xFF0000
#define KERNEL_LIMIT 0x1000000
#define LAPIC_PAGE 0xFEC00000
#define LAPIC_ADDR 0xFEE00000

// IO PORTS
#define MASTER_PIC_COMMAND_PORT 0x20
#define MASTER_PIC_DATA_PORT 0x21
#define SLAVE_PIC_COMMAND_PORT 0xA0
#define SLAVE_PIC_DATA_PORT 0xA1
#define PIT_COUNTER_1 0x40
#define PIT_COUNTER_2 0x41
#define PIT_COUNTER_3 0x42
#define PIT_COMMAND_PORT 0x43
#define PIT_DATA_PORT_CHANNEL_0 0x40
#define KEYBOARD_STATUS_PORT 0x64
#define KEYBOARD_DATA_PORT 0x60
#define KEYBOARD_PORT_B 0x61
#define PRIMARY_ATA_DATA_REGISTER 0x1F0
#define PRIMARY_ATA_SECTOR_COUNT_REGISTER 0x1F2
#define PRIMARY_ATA_SECTOR_LOWBYTE_NUMBER 0x1F3
#define PRIMARY_ATA_SECTOR_MIDBYTE_NUMBER 0x1F4
#define PRIMARY_ATA_SECTOR_HIGHBYTE_NUMBER 0x1F5
#define PRIMARY_ATA_DRIVE_HEADER_REGISTER 0x1F6
#define PRIMARY_ATA_COMMAND_STATUS_REGISTER 0x1F7
#define ATA_READ 0x20
#define ATA_WRITE 0x30

// Constants
#define NULL 0
#define KEYBOARD_BUFFER_SIZE 0x40
#define INTERRUPT_MASK_ALL_ENABLED 0x0
#define INTERRUPT_MASK_SYSTEM_TIMER_ONLY 0xFE
#define INTERRUPT_MASK_KEYBOARD_ONLY 0xFD
#define INTERRUPT_MASK_SYSTEM_TIMER_AND_KEYBOARD_ONLY 0xFC
#define INTERRUPT_MASK_ALL_DISABLED 0xFF
#define INTERRUPT_END_OF_INTERRUPT 0x20
#define BLOCK_SIZE 0x800
#define SECTOR_SIZE 0x200
#define CACHE_SIZE 168  // Number of 512 byte sectors. 168 = 21 Pages (0x15000 hex bytes)
#define PAGE_SIZE 0x1000
#define ENTRIES_PER_PAGE_TABLE 0x400
#define MAX_PGTABLES_SIZE 0x6000
#define USER_HEAP_PAGES 0x40
#define HEAP_OBJ_SIZE 0x100
#define HEAP_OBJ_USABLE_SIZE ((uint32_t)HEAP_OBJ_SIZE - 2) // 1 byte for PID and and extra byte for null
#define MAX_HEAP_OBJECTS 0x400
#define HEAP_SIZE ((uint32_t)(HEAP_OBJ_SIZE * MAX_HEAP_OBJECTS))
#define KERNEL_HEAP_OBJ_SIZE 0x402
#define KERNEL_HEAP_OBJ_USABLE_SIZE ((uint32_t)KERNEL_HEAP_OBJ_SIZE - 2) // 1 byte for PID and and extra byte for null
#define KERNEL_MAX_HEAP_OBJECTS 0x300
#define KERNEL_HEAP_SIZE ((uint32_t)(KERNEL_HEAP_OBJ_SIZE * KERNEL_MAX_HEAP_OBJECTS))
#define SEMAPHORE_SIZE 0x10
#define MAX_SEMAPHORE_OBJECTS 0x80
#define TASK_STRUCT_SIZE 192
#define PROC_SLEEPING 0x1
#define PROC_RUNNING 0x2
#define PROC_ZOMBIE 0x3
#define PROC_KILLED 0x4
#define MAX_PROCESSES 0x20
#define MAX_PROCESS_SIZE 0x1000000
#define PAGEFRAME_MAP_SIZE 0x1800
#define MAX_FILE_DESCRIPTORS 0xF
#define MAX_SYSTEM_OPEN_FILES 0x40
#define MAGIC_ELF 0x464C457F
#define ELF_LOAD_DYNAMIC_LIBRARIES 0xFF
#define DYNAMIC_LIBRARIES_SIZE 0x40000
#define ELF_PROGRAM_HEADER_SIZE 0x20
#define PT_LOAD 1
#define INODE_SIZE 0x80
#define EXT2_SECTOR_START 0x200
#define EXT2_SUPERBLOCK_SECTOR_START (EXT2_SECTOR_START + (BLOCK_SIZE / SECTOR_SIZE))
#define EXT2_NUMBER_OF_DIRECT_BLOCKS 0xC
#define EXT2_FIRST_INDIRECT_BLOCK 0xC
#define EXT2_BLOCKS_PER_INDIRECT_BLOCK (BLOCK_SIZE / sizeof(uint32_t))
#define EXT2_DIRECTORY_ENTRY_FILE 0x8
#define EXT2_DIRECTORY_ENTRY_DIR 0x4
#define KERNEL_TEMP_INODE_LOC_SIZE (PAGE_SIZE * 2)
#define KERNEL_WORKING_DIR_TEMP_INODE_LOC_SIZE (PAGE_SIZE * 2)
#define KERNEL_WORKING_DIR_SIZE (PAGE_SIZE * 2)
#define MEGABYTE 1048576
#define MAX_FILES_PER_DIRECTORY 0x40
#define INODES_PER_BLOCK (BLOCK_SIZE / INODE_SIZE) 
#define SUPERBLOCK 0x0
#define GROUP_DESCRIPTOR_BLOCK 0x1
#define ROOTDIR_BLOCK 0x207
#define ROOTDIR_INODE 0x2
#define SECOND_PROC_START_SECTOR 0x1F0
#define SOUND_MODE_3_SQUARE_WAVE 0xB6
#define SECONDS_IN_MIN 60
#define SECONDS_IN_HOUR 3600
#define SECONDS_IN_DAY 86400
#define SECONDS_IN_YEAR 31536000
#define PIT_FREQUENCY 1193182
#define SYSTEM_INTERRUPTS_PER_SECOND 150
#define PIPE_BUF_SIZE 0x400
#define GOTE_TYPE_BUFFER 0xFFFFFFFF
#define GOTE_TYPE_FILE 0xFFFFFFFE
#define GOTE_TYPE_PIPE 0xFFFFFFFD
#define GOTE_TYPE_SOCKET 0xFFFFFFFC
#define KERNEL_LOG_TYPE_SIZE 0x10
#define KERNEL_LOG_DESC_SIZE 0x28
#define KERNEL_LOG_MAX_EVENTS 0x300
#define SYSCALL_FAIL 0xFFFFFFFF
#define SYSCALL_SUCCESS 0x0
#define PROCESS_EXIT_CODE_SUCCESS 0x0
#define PROCESS_EXIT_CODE_MALLOC_FAILED 0x1
#define PROCESS_EXIT_CODE_INPUT_FILE_FAILED 0x2
#define PROCESS_EXIT_CODE_MALFORMED_OUTPUT 0x3
typedef uint8_t *va_list;
#define va_start(ap, last) (ap = ((uint8_t *)&(last) + sizeof(last)))
#define va_arg(ap, type)   ((ap) += sizeof(type), *((type *)(ap - sizeof(type))))
#define va_end(ap)


// Network Interface Card - NE2000 Registers
#define NE2000_BASE_PORT 0x300
#define NE_CR 0x00
#define NE_PSTART 0x01
#define NE_PSTOP 0x02
#define NE_BOUND 0x03
#define NE_TPSR 0x04
#define NE_TBCR0 0x05
#define NE_TBCR1 0x06
#define NE_ISR 0x07
#define NE_RSAR0 0x08
#define NE_RSAR1 0x09
#define NE_RBCR0 0x0A
#define NE_RBCR1 0x0B
#define NE_RCR 0x0C
#define NE_TCR 0x0D
#define NE_DCR 0x0E
#define NE_IMR 0x0F
#define NE_BNRY 0x03
#define NE_CURR 0x07

// User Interface
#define ASCII_HORIZONTAL_LINE 0xC4
#define ASCII_VERTICAL_LINE 0xB3
#define ASCII_UPPERLEFT_CORNER 0xDA
#define ASCII_UPPERRIGHT_CORNER 0xBF
#define ASCII_LOWERLEFT_CORNER 0xC0
#define ASCII_LOWERRIGHT_CORNER 0xD9
#define COLOR_GREEN 0x3
#define COLOR_WHITE 0xF
#define COLOR_LIGHT_BLUE 0x9
#define COLOR_RED 0xC

// Permissions
#define PG_KERNEL_PRESENT_RW 0x3
#define PG_USER_PRESENT_RO 0x5
#define PG_USER_PRESENT_RW 0x7
#define PAGEFRAME_AVAILABLE 0x00
#define KERNEL_OWNED 0xFF
#define RDONLY 0x1
#define RDWRITE 0x2

// System Calls
#define SYS_SOUND 0x1
#define SYS_OPEN 0x2
#define SYS_WRITE 0x3
#define SYS_CLOSE 0x4
#define SYS_PS 0x5
#define SYS_EXEC 0x6
#define SYS_EXIT 0x7
#define SYS_FREE 0x8
#define SYS_MMAP 0x9
#define SYS_KILL 0xA
#define SYS_SWITCH_TASK 0xB
#define SYS_MEM_DUMP 0xC
#define SYS_UPTIME 0xD
#define SYS_SWITCH_TASK_TO_PARENT 0xE
#define SYS_WAIT 0xF
#define SYS_DIR 0x10
#define SYS_TOGGLE_SCHEDULER 0x11
#define SYS_SHOW_OPEN_FILES 0x12
#define SYS_CREATE 0x13
#define SYS_DELETE 0x14
#define SYS_OPEN_EMPTY 0x15
#define SYS_CREATE_PIPE 0x16
#define SYS_READ 0x17
#define SYS_OPEN_PIPE 0x18
#define SYS_NET_SEND 0x19
#define SYS_SHOW_GLOBAL_OBJECTS 0x1A
#define SYS_CREATE_NETWORK_PIPE 0x1B
#define SYS_NET_RCV 0x1C
#define SYS_WHAT_PID_AM_I 0x1D
#define SYS_MEM_DISASSEMBLY 0x1E
#define SYS_SECTOR_TO_VIEW 0x1F
#define SYS_BLOCK_TO_VIEW 0x20
#define SYS_ELF_HEADER_TO_VIEW 0x21
#define SYS_INODE_TO_VIEW 0x22
#define SYS_KERNEL_LOG_VIEW 0x23
#define SYS_CHANGE_DIR 0x24
#define SYS_MOVE_FILE 0x25
#define SYS_GET_INODE_STRUCT 0x26
#define SYS_CHANGE_FILE_MODE 0x27
